---
title: "The Freedom of Wisdom's Body: Well-Being in Humanistic Management"
author: William G. Foote
date: "`r Sys.Date()`"
bibliography: wisdom.bib
abstract: Wisdom cannot be taught, it can only be learned. Wisdom cannot managed, it only can be enabled. If this is true, then from whom and by how effected? What is the content of wisdom, its natural end, its design? Indeed, what is the role of wisdom in humanistic management? If this aphorism admits nuance as to the enabling and the managing, what are those additional elements we might grasp to intend humanistic management? 
output: pdf_document
--- 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Wisdom cannot be taught, it can only be learned. Wisdom cannot managed, it only can be enabled.^[Herman @Hesse1998siddhartha, _Siddhartha_: "Wisdom cannot be imparted. Wisdom that a wise man attempts to impart always sounds like foolishness to someone else ... Knowledge can be communicated, but not wisdom. One can find it, live it, do wonders through it, but one cannot communicate and teach it.” (Ibid., 90). From Socrates: “Then when I began to try to show him that he only thought he was wise and was not really so, my efforts were  resented both by him and by many of the other people present. However, I reflected as I walked away. Well, I am certainly wiser than this man. It is only too likely that neither of us has any knowledge to boast of, but he thinks he knows something which he does not know, whereas I am quite conscious of my ignorance. At any rate it seems that I am wiser than he is to this small extent, that I do not think that I know what I do not know.” (Plato, _Apology_ 21c-d, [@Hamilton1961dialogues, 7-8]). "Sapientia est ordinare et iudicare." (Aquinas, _Summa Theologiae_, I.1.6). The wise person orders and judges.] If this is true, then from whom and by how effected? What is the content of wisdom, its natural end, its design? Indeed, what is the role of wisdom in humanistic management? If this aphorism admits nuance as to the enabling and the managing, what are those additional elements we might grasp to intend humanistic management?^[The _intention_ of being a humanistic manager is ultimately, according to [@lonergan1992insight], p. , the self-affirmation of the knower, here the manager. The verb _intend_ derives from the Latin verb _tendere_, to strive for, exert oneself, endeavor, grasp at, stretch, incline, persist, all with moral nuance. "We are not enough to lean against or to strive." ("nec nos obniti contra nec tendere tantum Supplicimus." Virgil _Aeneid_, 5, 21). More Virgil, and more nuance, speaking of Aeneas and his followers, mythical founder of Rome: "neither tarry nor rest; they persist to a vast struggle." ("nec mora nec requies; vasto certamine tendunt." Ibid., 12, 553). With Cicero at the end of the Roman _res publica_, and the beginning of the autocratic rule of Julius Caesar, _Dictator_,"what does he strive for, to what end do his efforts grasp at." ("quid tendit? cum efficere non possit, ut, ...", Cicero, _De Finibus_, 2,5,16) These are my translations supported by @LewisShort1907new, p. 1852-1853.]

"Even though young, I do have an opinion:/ Suppose everyone were born with full knowledge and wisdom, I believe that's best in every way. / But if this is not the case, and it normally isn't, / Then learn from a thought well spoken.” (Sophocles, _Antigone_ 719-22)^[My translation, is really, as all translations end up being, an elaborate paraphrase, in this case, of the literal Greek. We might further instruct ourselves through this translation of the Greek, _gnome gar ei tis kath' emou neoterou / prosesti, phem' egoge prebeuein polu / phunai ton andra pant' epistemes pleov:/ ei d'ouv, philei gar touto me tautei rhepeiv, / kai tov legovtov eu kalov to manthanein._ We pull from a few lines prior to Haemon's announcement of need for wisdom. "And in the same way the pilot who keeps the sheet of his sail taut and never slackens it, upsets his boat, and voyages thereafter with his decking underwater. Father, give way and allow a change from your rage. For if even from me, a younger man, a worthy thought may be supplied, [720] by far the best thing, I believe, would be for men to be all-wise by nature. Otherwise—since most often it does not turn out that way—it is good to learn in addition from those who advise you well." ([trans., Sir Richard Jebb, ed.](https://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.01.0186%3Acard%3D681) ]
] @Schindler2021politics, 101, quotes this phrase by Haemon to his father Creon to illustrate how different a kind of knowledge wisdom represents. What comes before is the stuff of every complex and muddled decision in every organization. Polyneices fought and died for his city. Creon the ruler of the city refused to bury him. Antigone is going against the rule of the city, Creon's city, where city is our whole civilization (Lat., _civitas_), She will bury, as is proper to the gods, and really, her conscience, her brother Polyneices. She has been forbidden to do so. Creon will enforce the penalty for failure to follow the city's rules and execute her. Haemon loves her and will follow her possibly to his death, certainly to hers. Greek tragedy is at its Sophoclean height of weighing, by a human, the god's themselves in a human decision! This is the stuff of wisdom, the formed conscience to discern the right action in a particular circumstance, whatever the maximized utility function might indicate, and then follow through. There is a principle, a grounding, at work in the young person making these assertions to learn the right and wrong things to do. That is hardly sufficient though. Knowledge (episteme), experience (phronesis), and wisdom (sophia) is not static, it goads the person, our humanistic manager, to learn (manthanein) and apply with action. This is the freedom of wisdom's actions in a particular situation, with concrete outcomes, an ensemble we will identify as wisdom's body. So goes every complex community of persons, that is to say every manager's conundrum in the particulars of the managed persons in complex organizations. The persons in the community, the community itself, propelled through the time and spaces of markets, contracts, product launches, regulatory oversight, powers reserved and delegated by boards, all are part and parcel of wisdom's body cloaked in freedom.

Early modern science, at least beginning with @Descartes1998discourse and  @Bacon2000novumorganon, revolutionized the making we do as managers of anything, our technology, or as the classical Greeks called it, _techne_. They did so by one simple move: declare that the end of all human striving is freedom, of choice that is. Because we are free to choose we can literally make anything we want, and we do from the making of corporate governance policy, to enforcement of contracts, to products and their launches into otherwise uncharted market spaces. In doing so, these revolutionaries literally professed the inability of science to deal with or include in their scientific analysis questions of ultimate causes, which algebraic simplicity we would call the dynamically changing manifold of meaning. They inverted the classical paradigms of be-ing precedes essence, works, even freedom and any kind of knowledge. The classical paradigm places the realm of wisdom as naturally embedded in persons, all persons, who are aquaintenances as well some who are outright enemies of wisdom. The scientific method sets its own boundaries and thus limits its grasp to any subsuming levels of inquiry. It literally cannot ask questions about itself as itself. Thus science as inferring a knowledge of things and their relations to other things by us leads to an absolute positivism. Because science can only observe and theorize and experiment the material causes of anything at all, it must conclude all discussion in a materialistic reduction of schemes of any realities beyond the material to the material. How inappropriate is that! In the scientific context freedom is what is sought for its own good. This is the freedom to explore at will without consequence. But can we even use the scientific method to explore the freedom of wisdom, of wisdom embodied in the humanistic manager, in complex networks of communities of persons?

Part of the problem in understanding the revolutionary inversion of freedom preceding be-ing (exist-ing) is the meaning of "self-determination," what it means and where it resides in the person and in the community of persons. If "self-determination" simply means "free to choose," then the will to choose one action versus another must be self-contained. This is not the will of Haemon the youth. Sophocles, and many a manager, might contend that the very notion of being self-contained is nonsense if only because there must be causes, reasons, for the causes of anything.^[@Dadosky2014loneganwisdom locates wisdom in Bernard @lonergan1992insight's _Insight_ squarely in the "self-affirmation of the knower." (Ibid., 257, [@Dadosky2014loneganwisdom, 48]). In the context of lock-down orders forcing de facto social isolation @Clair2021effects find that: " Perceived social isolation was associated with poor life satisfaction across all domains, as well as work-related stress, and lower trust of institutions. Higher levels of substance use as a coping strategy was also related to higher perceived social isolation. The experience of perceived social isolation has significant negative consequences related to psychological well-being." (Ibid., 1). The SARS-2 pandemic provided a glimpse into the impact of social isolation, a condition not unlike anyone who self-determines with a self-contained will to well-being.] After all the will is formed by every past decision, with good or bad, correct or incorrect outcomes, and every relationship as well, along with a fundamental drive to go beyond itself to the highest good. Like everything else about persons, the will to act on reasonable grounds is in a course of vertical finality to the good as well as a horizontal finality of ever increasing horizons, write relationships here, of transcendence.
Then we confront this quip by the youngster-in-love Haemon to his father Creon about Antigone's anti-polity, declared as blasphemous, activity. Haemon humbles first himself. Then he speaks the principle of wisdom and its deployment in the particular concrete situation he and the city is in. As @Schindler2021politics puts it:

"His is an image of wise ignorance (docta ignorantia): one accepts that one does not know by following the one who does, and thus one shares in the reality of that wisdom without claiming to be the source of that wisdom oneself." (Ibid., 101)

This essay builds on Vianney Domingo and Dominec Mele's call for a thorough "rethinking" of management from the perspective of the "classical tradition" to help form the role of wisdom in properly humanistic management. [@DomingoMele2022rethinking]. Here the "classical" handing down of a notion of wisdom will historically include modernity and post-modernity as goads to applying the dynamically moving tradition to changing times and situations.^[Much in line with a move to rethink management Josef Pieper exclaims that "... the decisive unity of the human race cannot be based on or guaranteed by realizing a political 'One World' or any kind of unanimity of 'cultural wills,' no, not by a shared respect before art and science, not by the technical possibilities of communication throughout the planet earth, not by a universal world language, whether it be English or Esperanto or Chinese, not even by international organizations for athletic competition. Rather, real unity among human beings has its roots in nothing else but the common possession of tradition in the strict sense — I mean, our sharing in common the sacred tradition that goes back to God’s words." [@Pieper2008tradition, 68 ]. ] We proceed in the classical tradition by a priority of spirit over matter, thus the title wisdom's body, in the genitive case, that wisdom precedes and infuses the bodies of persons and of communities of persons. The case distinction is important as we live a logical, natural, in a word ontological, contradiction. @DLSchindler2013pelagianism labels this contradiction "technological ontology," and even more descriptively, "ontological semi-pelagianism." If anything worthwhile is indeed what we worship, put first and foremost in devotion and reverence, then technology has become a "positivist religion" enabled by a "voluntarist notion of freedom" and an "instrumentalist idea of reason." (Ibid., 245). 

Several inversions follow: freedom precedes being, power precedes authority, institutions precedes persons. For example, through an inversion, the origin of our institutions resides in voluntary means to an end by individuals. One such example is the so-called need to coerce, say by incentive or by sanction, in an organization or community. This inverts the classical world-view of community as naturally emanating from the social character of persons in their very given-ness as beings. The inversion results in a primacy of personal choice, a negative sort of freedom, as the goal of all rights enshrined in constitutions and corporate policies, the _voluntarist notion of freedom_. This goal is achieved by any means including the use of persons as means to an end, the _instrumentalist notion of reason_. If by "religion" we mean a devoted, if not also enthusiastic, commitment to beliefs in something or someone (from the Lat. _religare_, to bind), then this inversion implies a "show me" the money, honors, results, ignoring or even refusing the experience of intuition, faith, in fact, anything non-material, the _positivist religion_. In the end if a person's dignity resides naturally in the given-ness of the being of the person, then this inversion not only erodes this dignity, but it also eliminates it as substantial to the person. The inversion thus eliminates the ground for a humanistic management. I argue in this essay that the ultimate antidote to this basic inversion, present in most modern and post-modern institutions, including business organizations, is wisdom.^[@Costanza1952catholicpoliteia1 notes the inversions we encounter daily and the "illusory" nature of the sufficiency of knowledge, and the power it provides: "The classical idea of a good life through knowledge (which Pelagius was to incorporate into his heresy) was wholly illusory. A process through education, either as intellectual discipline or moral habituation or both, cannot but lead to the deceptive and flattering ideal in utter disregard of the sobering fact of historical experience, that man cannot attain felicity in a mere world-immanent concept and endeavor. Born of Greek intellectualism and Roman voluntarism, and tempered by the turbulent experiments of the _polis_ and the more enduring results of Roman statecraft, the politeia depended for its survival on a number of arbitrary identifications-religion, morals, politics, the immanent cosmic reason equated subjectively to "mind", power with nature, and the Ultimate Good with the life of the City." (Ibid., 92) The "life of the City" is our complex transcultural organization embedded in a network of markets. Pelagius (c.355 – c.420 AD) was a British monk who preached the priority of free choice and knowledge as the path to salvation, in other words, humans are natively endowed to save themselves. [@Britannica2024pelagius].]

In the spirit of conversion, rather than inversion, and While we often speak of the notion of wisdom, here we begin with the wise person, the _sophos_, the sage, -manager and -leader in our case, who "becomes as close to the divine as one can, and that again is to be righteous with the help of wisdom." (Plato _Theaetetus_ 176b,[@Hamilton1961dialogues,881]). There is a dynamic in "becoming" and a good of order in "righteous." The order of "righteous" is the very ordering of reality, the concrete here and now, to the good. The good comes from outside the sage-manager, -leader, in the "divine." The work of the sage is to "get as close" as possible, the here and now concrete particular notwithstanding, to the source of all goodness. The becoming begins with a "sense of wonder the mark of the philosopher ... [p]hilosophy indeed has no other origin." (Ibid., 155c-d,860). The evolving state of being "righteous" involves the sage in the order of the universe, of the making and doing, in the self- reflective knowing what one does not know. Anything else is foolish, naive, stupid, even malicious. (Ibid., 176c-d,881).

So what does the sage-manager need to grow into and experience? The pinnacle of the Aristotelian wisdom tradition is the overarching and subsuming, _sophia_, wisdom as knowledge of ultimate causes, the "divine" in Socrates' terms. Ultimate causes include those which are intelligible, and those which are not. The ultimate causes are the reasons for other causes, the meaning of meaning. Intelligible causes are patterns we detect, for example, when we run probabilistic models of the impact of stress on worker quality. Causes are not probabilities and certainty is not the goal of wisdom, only the participation of the sage-manager in the promotion of the good itself is the end, the goal. What is not intelligible but nonetheless happens is what is not predicted by the model. Causes, both intelligible and un- or not-yet-intelligible imply a right ordering of networks of cause and effect. The work of the wise manager is thus to put into an intelligible order, the network of causes and effects, even the otherwise unintelligible. 

The whole idea of "putting things in order" is what is meant here by justice. The wise manager is then also a just manager. But justice as right ordering would then demand that the wise manager as just orders according to the greater good for all stakeholders, not just the maximizing good for the greatest number. The logic of the just order is not simply an optimality in the here and the now, but it is an ordered sequence of transcending goodness, especially for those who are most vulnerable and excluded.

Subsisting in _sophia_ is _nous_, the residence of our ability to discern what is and what is not in general and in particular, as well as _episteme_, knowledge of necessary truths. Auxiliary to the manifold virtue of _sophia_, in the sense of serving _sophia_, is the grounding of practical causes through _phronesis_, prudence in a process of practical discernment, _theorein_.^[We follow the typology in Aristotle, _Nichomachean Ethics_ 1142b, [@Rackham1926nicomachean, 337-339]. ] Two interesting linguistic details stand out. The first is that _phronesis_ is the faculty of a _so-phro-sune_, the sound-discerning person. (Ibid., 1142b11). The second detail follows with @Onians1951 who points out that the ancients thought about the seat of discernment as residing in the top of the diaphragm, the $phren$, both regulating breath, and by extension not simply metaphorical, action by the person. @Town2021gestalt and @Tsai2024phronesis fold into this discussion the growing awareness of viewing phronetic wisdom as practical intelligence supported by emotion. @Baltes1990toward construct a psychological ontogeny of wisdom as expertise, skills to discern and carry out the implications of the discernment. Given an anthropology of gift whose design is love as the willing of the good for any other, that is, an _agapic_ love, wisdom in management takes on a grounding principle for pragmatic phronesis, that is, prudence, which integrates skill models and expertise with the guidance to apply the right skills to the right situation, hopefully in time, and directed to the ultimate causes of causes and their effects.  

The essay proceeds from this formal, quite abstract, design by mapping the infusion of wisdom into humanistic management pedagogy, practices, and policies. The next section delves further into the nature of wisdom, replete with managerial expressions, especially the end which such wisdom seeks. This end or goal or prupose will be the manifold support of the dignity of humans and their well-being. We will ask what design befits managerial wisdom as knowledge and expertise. Here a typology awaits us. This leads us to delineate the resources supporting managerial wisdom, the _techne_ of wisdom, including skill sets, roles in organizations, development of persons, and workplace practices, including the provision and governance of persons. Lastly in this initial quest we attend to the person, the anthropology of gift who effects wisdom, expertise, using skills, communication, cajoling, the setting up of situations in dynamically changing organizations to seek the good of wisdom for the sake of human dignity and well-being.

After this discussion we attend to implications for managerial action. Implications will be along intersecting dimensions of humanistic management pedagogy, practices, and policies. In a second section along pedagogical lines we will discuss academic and non-academic modes of learning to learn in increasingly complex situations, focusing of the knowing, not the know-how or know-about, as important as these content areas are. But educating for wisdom which updates the balance approach of Robert @Sternberg2001wisdom for humanistic managment educations is a nurturing effort of growing in discernment and contemplation, not simply logic and exposition of results for decision makers. @Kaefer2022teaching provide a practical example of applying Ignatian pedagogical principles to data analytics including discussions of context, horizons, the known and unknown, the greater good. Such efforts will continue to involve the care of the whole student as person along with cross-disciplinary cohesion of the otherwise disparate specializations of knowledge.

Pedagogical implications very naturally lead to humanistic management practices in a third section of this essay. It is these practices academic and non-academic processes and institutions intend to develop in their initiates. Chief among these are approaches to decision making which build on the trade-off analyses of consequentialist-rational choice models, but do not stop there. These approaches will incorporate systemic approaches to humanistic decision making and design of communities of persons with multiple and dynamic objectives, among them the minimization of the maximum loss for the most vulnerable. But knowledge of tradeoffs is insufficient as wisdom transcends and subsumes the pattern-seeking nature of trade-offs to incorporate the surd, the seemingly irrational, the unsettling "gut" feeling that all is not quite yet right ordered.^[Even though we may consume food and drink that tastes good, has healthy components we need, we can still get the all too real diaphragmatic feeling of indigestion. How much more so when we consider whatever the rational choice analysis indicated, we might still counter the analysis with conscience, the heart, moral indigestion.] As @Tarandach2021healing develop the notion of healing practices in organizations, the systemic component registers a care, concern, and need to heal in a network of communities of persons across cultural boundaries, not just geographical and political lines. @Wheeler2024soothing develop practical healing interventions to ensure the sustainable success of creativity in organizations through moderation and mediation of negative affects by self-affirmation, a result of enabling wisdom through positive practices.

Practices such as these will imply the need for humanistic provisioning and governance to align actions with wisdom and its inculcation across the persons who are the organization, including the promotion of principles of subsidiarity and solidarity all deposited in a fourth section. The heart of such policies would imply the insinuation of communal discernment of strategies and supporting tactics in the management of the arc of the organization as community of persons. Wisdom in organizations is really the wisdom evinced by persons in their actions. As @Kleymann2010SaintBenedict and @Carey2023ignatian discover that the wisdom embedded in policy and leadership bespeaks the mutual care, even the point of acceding one another in generosity, such as indicated @Tarandach2021healing and recommended by @Sternberg2001wisdom.  With such aspirations for policy we are back to pedagogy and practice interdependently mediating and moderating one another.
 
The essay will conclude with suggestions for presenting these expanding horizons of humanistic management wisdom. At the core will always be the sage person, not the organization, not the technology. We will thus conclude with a suggested typology to align the rethinking frame offered by the classical tradition with suggestions for humanistic management research constructs along psychological, economic, sociological, anthropological (cultural and philosophical), and ethical dimensions of managerial activity.

# References
